# docker-compose.yml
# Используй вместе с .env (но есть дефолты через ${VAR:-...})

services:
  mysql:
    # Надёжная ветка для локалки. Можно поменять на mysql:8.4 без доп. флагов.
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      # Не задаём MYSQL_DATABASE/USER/PASSWORD, чтобы не привязывать к одной БД.
      # БД под проекты создавай руками или скриптом (db-ensure).
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p$$MYSQL_ROOT_PASSWORD | grep 'mysqld is alive'"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  # PHP 8.3 workspace
  workspace83:
    build:
      context: ./workspace
      args:
        PHP_TAG: "${PHP83_TAG:-8.3-cli}"
        NODE_MAJOR: "${NODE_MAJOR:-20}"
    working_dir: /var/www
    volumes:
      - ${HOST_PROJECTS_DIR:-../}:/var/www
      - composer_cache:/tmp/composer
      - node_cache:/home/dev/.npm
      - ./logs:/var/log/devbox
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      XDEBUG_MODE: ${XDEBUG_MODE:-debug}
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
      PHP_IDE_CONFIG: serverName=php-devbox-83
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      mysql:
        condition: service_healthy
    command: bash -lc 'php -v && node -v && npm -v; tail -f /dev/null'
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      # Публикуем диапазоны портов, чтобы скрипты могли гибко выбирать
      - "${APP_PORT_RANGE_83:-28080-28120}:${APP_PORT_RANGE_83:-28080-28120}"
      - "${VITE_PORT_RANGE_83:-28130-28180}:${VITE_PORT_RANGE_83:-28130-28180}"
    restart: unless-stopped

  # PHP 7.4 workspace
  workspace74:
    build:
      context: ./workspace
      args:
        PHP_TAG: "${PHP74_TAG:-7.4-cli}"
        NODE_MAJOR: "${NODE_MAJOR:-20}"
    working_dir: /var/www
    volumes:
      - ${HOST_PROJECTS_DIR:-../}:/var/www
      - composer_cache:/tmp/composer
      - node_cache:/home/dev/.npm
      - ./logs:/var/log/devbox
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      XDEBUG_MODE: ${XDEBUG_MODE:-debug}
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
      PHP_IDE_CONFIG: serverName=php-devbox-74
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      mysql:
        condition: service_healthy
    command: bash -lc 'php -v && node -v && npm -v; tail -f /dev/null'
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "${APP_PORT_RANGE_74:-28200-28240}:${APP_PORT_RANGE_74:-28200-28240}"
      - "${VITE_PORT_RANGE_74:-28250-28290}:${VITE_PORT_RANGE_74:-28250-28290}"
    restart: unless-stopped

volumes:
  mysql_data:
  composer_cache:
  node_cache:
